headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "D:\\PORTFOLIO-site"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"

[[headers]]
for = "*.html"

[headers.values]
Cache-Control = "public, max-age=3600"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=86400"

[[redirects]]
from = "/tmoc"
to = "/tmoc-built/index.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]